#!/bin/bash
# DO NOT EDIT! THIS FILE IS AUTOGENERATED BY bin/docker2bash.sh!
# Make your changes to $XLRDIR/Dockerfile and run build config to
# generate this file and submit it with your Dockerfile changes

DOCKERPWD=$PWD
DOCKERUSER="`id -un`"
SRCDIR=$PWD
if [ `id -u` -ne 0 ]; then sudo "$0" "$@"; exit $?; fi
if [ -z "$CONTAINER_USER" ]; then echo >&2 "WARNING: \$CONTAINER_USER not specified in the environment!"; fi
if [ -z "$CONTAINER_UID" ]; then echo >&2 "WARNING: \$CONTAINER_UID not specified in the environment!"; fi
if [ -z "$APT_PROXY" ]; then echo >&2 "WARNING: \$APT_PROXY not specified in the environment!"; fi
rm -f /etc/profile.d/buildenv.sh
set -ex
# FROM centos:6
# MAINTAINER Xcalar Inc. <support@xcalar.com>

echo export UPDATED_AT=20161006 | tee -a /etc/profile.d/buildenv.sh && source /etc/profile.d/buildenv.sh

cd $DOCKERPWD && yum update -y || exit $?
cd $DOCKERPWD && yum localinstall -y http://repo.xcalar.net/xcalar-epel-release.el6.rpm https://centos6.iuscommunity.org/ius-release.rpm || exit $?
cd $DOCKERPWD && yum install -y centos-release-scl curl tar bzip2 gzip || exit $?
cd $DOCKERPWD && yum install -y devtoolset-3-gcc devtoolset-3-binutils devtoolset-3-gcc-c++ clang clang-devel clang-analyzer llvm libcxx libcxx-devel make git autoconf automake ctags libtool python27 python27-devel python27-libs python27-pip bzip2-devel zlib-static || exit $?
cd $DOCKERPWD && yum install -y cmake libxml2-devel libxslt-devel libgsasl-devel libuuid-devel krb5-devel || exit $?
cd $DOCKERPWD && yum install -y mawk sudo libbsd-devel jansson-devel libarchive3-devel libarchive3 ncurses-devel libcap-devel libaio-devel ncurses-devel openssl-devel || exit $?
cd $DOCKERPWD && yum install -y ruby193-ruby-devel ruby193-ruby ruby193-rubygem-bundler vim-enhanced bash-completion rpm rpm-devel rpmdevtools rpm-build || exit $?
cd $DOCKERPWD && yum install -y perl-TAP-Harness-Archive perl-TAP-Harness-JUnit perl-core cmake3 || exit $?
cd $DOCKERPWD && yum install -y snappy snappy-devel bison yacc || exit $?
echo export PATH=/opt/rh/ruby193/root/usr/bin:/opt/rh/ruby193/root/usr/local/bin:/opt/rh/devtoolset-3/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin | tee -a /etc/profile.d/buildenv.sh && source /etc/profile.d/buildenv.sh
cd $DOCKERPWD && echo '/opt/rh/ruby193/root/usr/lib64' > /etc/ld.so.conf.d/ruby.conf || exit $?
cd $DOCKERPWD && echo '/opt/rh/devtoolset-3/root/usr/lib64' > /etc/ld.so.conf.d/devtoolset-3.conf || exit $?
cd $DOCKERPWD && ln -sfn /usr/lib64/liblzma.so.0 /usr/lib64/lzma.so.5 || exit $?
cd $DOCKERPWD && printf '#!/bin/bash\nsource /opt/rh/devtoolset-3/enable\nexport X_SCLS="`scl enable devtoolset-3 '"'"'echo $X_SCLS'"'"'`"\n' > /etc/profile.d/scl-devtoolset-3.sh || exit $?
cd $DOCKERPWD && printf '#!/bin/bash\nsource /opt/rh/ruby193/enable\nexport X_SCLS="`scl enable ruby193 '"'"'echo $X_SCLS'"'"'`"\n' > /etc/profile.d/scl-ruby193.sh || exit $?
cd $DOCKERPWD && printf '#!/bin/bash\nexport USER="`whoami`"\n' > /etc/profile.d/user.sh || exit $?
cd $DOCKERPWD && printf '#!/bin/bash\nexport LOGNAME="`whoami`"\n' > /etc/profile.d/logname.sh || exit $?
cd $DOCKERPWD && for pkg in `ls /etc/profile.d/scl-*.sh`; do source ${pkg}; done && ldconfig || exit $?

cd $DOCKERPWD && gem install --no-ri --no-rdoc fpm || exit $?
cd $DOCKERPWD && curl -sSL https://github.com/just-containers/s6-overlay/releases/download/v1.17.2.0/s6-overlay-amd64.tar.gz | tar zxf - -C / || exit $?
cd $DOCKERPWD && curl -sSL https://github.com/tianon/gosu/releases/download/1.7/gosu-amd64 > /usr/bin/gosu && chmod +x /usr/bin/gosu || exit $?


# ARG CONTAINER_USER
# ARG CONTAINER_UID
# ARG APT_PROXY

#Entrypoint CMD
#
#!/bin/bash
# DO NOT EDIT! THIS FILE IS AUTOGENERATED BY bin/docker2bash.sh!
# Make your changes to $XLRDIR/Dockerfile and run build config to
# generate this file and submit it with your Dockerfile changes

DOCKERPWD=$PWD
DOCKERUSER="`id -un`"
SRCDIR=$PWD
if [ -z "$CONTAINER_USER" ]; then echo >&2 "WARNING: \$CONTAINER_USER not specified in the environment!"; fi
if [ -z "$CONTAINER_UID" ]; then echo >&2 "WARNING: \$CONTAINER_UID not specified in the environment!"; fi
if [ -z "$APT_PROXY" ]; then echo >&2 "WARNING: \$APT_PROXY not specified in the environment!"; fi
rm -f /etc/profile.d/buildenv.sh
# FROM el6-base
# MAINTAINER Xcalar Inc. <support@xcalar.com>

echo export UPDATED_AT=20161006 | tee -a /etc/profile.d/buildenv.sh && source /etc/profile.d/buildenv.sh
cd $DOCKERPWD && yum localinstall -y http://repo.xcalar.net/xcalar-release-1.0-2.x86_64.rpm || exit $?
cd $DOCKERPWD && yum install -y autoconf-2.69 automake-1.14.1 libtool-2.4.6 boost-1.55 protobuf-devel-3.0.2 protobuf-compiler-3.0.2 protobuf10 editline-devel thrift-devel python27-xlrd python27-enum34 jemalloc-devel ccache cryptopp-devel cryptopp wamerican || exit $?

cd $DOCKERPWD && find /usr/ /lib*/ -name 'libltdl*.la' -delete || exit $?
cd $DOCKERPWD && ldconfig || exit $?
#RUN curl -sL https://bootstrap.pypa.io/get-pip.py | /opt/rh/python27/root/usr/bin/python

# ARG CONTAINER_USER
# ARG CONTAINER_UID
# ARG APT_PROXY

# vim: ft=Dockerfile:
#Entrypoint CMD
exit 0
