version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

  stepfunction:
    image: amazon/aws-stepfunctions-local
    ports:
      - '8083:8083'
    env_file: .env
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8010:8000'
    command: -jar DynamoDBLocal.jar -sharedDb
    env_file: .env
  jupyterhub:
    image: jupyterhub/singleuser
    ports:
      - '8888:8888'
    env_file: .env
