AWSTemplateFormatVersion: '2010-09-09'
Description: Create a role for Kinesis to parse S3 logs and discover their schema
Parameters:
  S3PermissionsPolicy:
    Description: Set of permissions policies you want to grant to AWS KinesisAnalytics
    Type: String
    Default: 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
Resources:
  KinesisServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'kinesisanalytics.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - !Ref 'S3PermissionsPolicy'
Outputs:
  KinesisServiceRoleARN:
    Description: Service role ARN for subsequent Kinesis calls
    Value: !GetAtt 'KinesisServiceRole.Arn'
