retainPolicy: False
s3RetainPolicy: Delete
efsRetainPolicy: Delete
workBucketRetainPolicy: Delete
licenseArg: True
logCopy: True
samAsg: False
enableSsh: True
enableSpareBucket: False
enableLifecycle: False
