#!/bin/bash
#
# See Dockerfile for notes about /opt/clang5
#
exec docker run --init --rm --name jenkins-aggregators-update --hostname jenkins-aggregators-update -v /netstore:/netstore -v /opt/clang5:/opt/clang5 jenkins-aggregators-update
