---
global:
  scrape_interval:     15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nomad'
    scrape_interval: 10s
    metrics_path: /v1/metrics
    params:
        format: ['prometheus']
    consul_sd_configs:
      - server: '10.10.5.18:8500'
        datacenter: xcalar-sjc
        tag_separator: ','
        services:
          - "nomad"
          - "nomad-client"
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: .*,http,.*
        action: keep
  - job_name: 'nomad_metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']
    consul_sd_configs:
      - server: '10.10.5.18:8500'
        datacenter: xcalar-sjc
        tag_separator: ','
        scheme: http
        services:
        - nomad-client
        - nomad
          #    tls_config:
      #      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        separator: ;
        regex: (.*)http(.*)
        replacement: $1
        action: keep
      - source_labels: [__meta_consul_address]
        separator: ;
        regex: (.*)
        target_label: __meta_consul_service_address
        replacement: $1
        action: replace
