#!/bin/bash

#Name=tag:aws:autoscaling:groupName,Values=$AWS_AUTOSCALING_GROUPNAME
ec2_find_cluster() {
    aws ec2 describe-instances \
        --filters Name=tag:$1,Values=$2 \
                  Name=instance-state-name,Values=running \
        --query "Reservations[].Instances[].[LaunchTime,AmiLaunchIndex,${3:-PrivateIpAddress}]" \
        --output text | sort -n | awk '{print $(NF)}'
}

mbfree() {
    local mb
    if ! mb=$(/bin/df -BM --output=size "$1" | tail -1 | tr -d ' M'); then
        return 1
    fi
    echo "$mb"
}


set -a
eval $(ec2-tags -s)
set +a

IPS=($(ec2_find_cluster ClusterName ${CLUSTERNAME}))
COUNT="${#IPS[*]}"
if [ $COUNT -eq 1 ]; then
    XLRROOT=/var/opt/xcalar
else
    if [ -n "$FILESYSTEMID" ]; then
        XLRROOT=/mnt/xcalar
        echo  "${FILESYSTEMID}:/ /efs   efs  _netdev,defaults 0 0" >> /etc/fstab
        mkdir -p /efs
        mount /efs
        mkdir -p /efs/cluster/${CLUSTERNAME}
        chown xcalar:xcalar /efs/cluster/${CLUSTERNAME}
        echo "${FILESYSTEMID}:/cluster/${CLUSTERNAME}  $XLRROOT  efs  _netdev,defaults 0 0" >> /etc/fstab
        mkdir -p $XLRROOT
        mount $XLRROOT
    fi
fi
XCE_LOGDIR=/var/log/xcalar

XCE_XDBSERDES=/ephemeral/data
MBSIZE=$(( $(mbfree $XCE_XDBSERDES) - 1000 ))

mkdir -p $XCE_XDBSERDES/serdes
chown xcalar:xcalar $XCE_XDBSERDES/serdes

cat > /etc/xcalar/default.cfg <<EOF
// ----------------------------------------------------------------------------
// ----------THESE PARAMS CONTROL CLUSTER CONFIGURATION------------------------
// ----------------------------------------------------------------------------

// Set to 0 or omit to get us to query the system
// Constants.TotalSystemMemory=25769803776

// Set to true to enforce TotalSystemMemory
// Constants.EnforceVALimit=true

// Set to true to enable network compression
// Constants.NetworkCompression=true

Constants.XcalarRootCompletePath=${XLRROOT}
Constants.XcalarLogCompletePath=${XCE_LOGDIR}

Constants.XdbSerDesMaxDiskMB=${MBSIZE}
Constants.XdbLocalSerDesPath=${XCE_XDBSERDES}/serdes
Constants.XdbSerDesMode=2

Thrift.Port=9090
Thrift.Host=localhost

// --- Start of auto-generated stuff ---
// Cluster management stuff. The following has been
// auto-generated by genConfig.sh
// Enabled BufferCacheLazyMemLocking due to virtualization: kvm
Constants.BufferCacheLazyMemLocking=true

Node.NumNodes=$COUNT
EOF
for i in $(seq 0 $((COUNT-1))); do
    cat >> /etc/xcalar/default.cfg <<EOF
Node.${i}.IpAddr=${IPS[$i]}
Node.${i}.Port=5000
Node.${i}.ApiPort=18552
Node.${i}.MonitorPort=8000
EOF
done

mkdir -p $XLRROOT/config
chmod 0700 $XLRROOT/config
/opt/xcalar/scripts/genDefaultAdmin.sh -u "${ADMIN_USERNAME:-xdpadmin}" -p "${ADMIN_PASSWORD:-Welcome1}" -e "${ADMIN_EMAIL:-info@xcalar.com}" > $XLRROOT/config/defaultAdmin.json
chmod 0600 $XLRROOT/config/defaultAdmin.json
chown -R xcalar:xcalar $XLRROOT/config

mkdir -p $XLRROOT $XCE_LOGDIR
chown xcalar:xcalar $XLRROOT $XCE_LOGDIR /etc/xcalar/*

#systemctl start xcalar
