createVpc: True
logGroup: False
logCopy: False
enableBaseURL: False
enableLicense: False
enableSpareBucket: False
enableScheduler: True
samAsg: False
enableLifecycle: False
enableSsh: True
enableDns: True
customAmi: False
maxClusterSize: 4
instance_types:
  - r5d.xlarge
  - r5d.2xlarge
  - r5d.4xlarge
  - r5d.8xlarge
  - r5d.12xlarge
  - r5d.16xlarge
  - r5d.24xlarge

