AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  AccessKey:
    Value: !Ref 'accesskey'
  SecretKey:
    Value: !GetAtt 'accesskey.SecretAccessKey'
  UserName:
    Value: !Ref 'user'
Parameters:
  UserName:
    Type: String
Resources:
  user:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref 'UserName'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  accesskey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'user'
