AWSTemplateFormatVersion: "2010-09-09"


Parameters:
  BucketName:
    Type: String
Resources:
  bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'BucketName'
  policy:
    Type: AWS::IAM::Policy
    Properties:
      Groups: {}
      Users: {}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowListing
            Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
            Resource: !Sub 'arn:aws:s3:::${bucket}'
          - Sid: AllowRwAccess
            Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:DeleteObject
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:GetObjectVersion
              - s3:ListMultipartUploadParts
              - s3:PutObject
              - s3:PutObjectAcl
            Resource: !Sub 'arn:aws:s3:::${bucket}/*'
          - Sid: VisualEditor2
            Effect: Deny
            Action: s3:DeleteBucket
            Resource: !Sub 'arn:aws:s3:::${bucket}'
Outputs:
  bucket:
    Value: !Ref bucket
  policy:
    Value: !Ref policy

